#!/usr/bin/env php
<?php

function e($message, $exit = false) {
    if (is_array($message)) {
        $tmp = '';
        foreach ($message as $msg) {
            $tmp .= $msg.PHP_EOL;
        }
        $message = $tmp;
    }

    echo $message;

    if ($exit === true) {
        echo PHP_EOL;
        exit;
    }
}

if (PHP_SAPI != 'cli') {
    e('Sorry! this script can only be access from CLI', true);
}

function help($exit = false) {
    e([
        'Usage: php system/install [BASE_URL] [DB_USER]:[DB_PASS]@[DB_HOST]/[DB_NAME]',
        PHP_EOL.'Which is:',
        '  BASE_URL  is your base url, example: http://localhost/my-app/, default: (empty)',
        '  DB_HOST   is mysql database hostname, default: localhost',
        '  DB_USER   is mysql database username, default: root',
        '  DB_PASS   is mysql database password, default: (empty)',
        '  DB_NAME   is mysql database name, default: (empty)',
        PHP_EOL.'Example Usage:',
        '  > php system/install http://localhost/my-app/ root:password@localhost/my_database',
        '  Or, if you have no password:',
        '  > php system/install http://localhost/my-app/ root:@localhost/my_database',
    ], $exit);
}

$base_url = '';

if ($argc > 1) {
    if (strtolower($argv[1]) == 'help') {
        help(true);
    }

    $base_url = $argv[1];
}

$dbConf     = $argc >= 3 ? 'mysql://'.$argv[2] : '';
$rajaongkir = getenv('RAJAONGKIR_API') ?: '';
$cleardb    = getenv('CLEARDB_DATABASE_URL') ?: false;
if ($cleardb) {
    $base_url = getenv('APP_DOMAIN');
    $dbConf = $cleardb;
}

$dbConf = $dbConf != '' ? parse_url($dbConf)                  : [];
$dbHost = isset($dbConf['host']) ? $dbConf['host']            : '';
$dbUser = isset($dbConf['user']) ? $dbConf['user']            : '';
$dbPass = isset($dbConf['pass']) ? $dbConf['pass']            : '';
$dbName = isset($dbConf['path']) ? substr($dbConf['path'], 1) : '';

$errors = [];

try {
    if (!empty($base_url) and $base_url != '/') {
        if (substr($base_url, 0, 4) != 'http') {
            throw new Exception('BASE_URL should containts scheme (e.g. http://localhost/)');
        }

        if (substr($base_url, -1) != '/') {
            throw new Exception('BASE_URL should trailed with slash (e.g. http://localhost/)');
        }
    } else {
        $base_url = '/';
    }

    $replacements = [
        "'baseurl' => ''" => "'baseurl' => '{$base_url}'",
        "'host' => ''"    => "'host' => '{$dbHost}'",
        "'user' => ''"    => "'user' => '{$dbUser}'",
        "'pass' => ''"    => "'pass' => '{$dbPass}'",
        "'name' => ''"    => "'name' => '{$dbName}'",
        "'key' => '',"    => "'key' => '{$rajaongkir}',",
    ];

    if (!file_exists($configSample = __DIR__.'/configs_sample.php')) {
        throw new Exception("configs_sample.php file not found.");
    }

    if (file_exists($configFile = __DIR__.'/configs.php')) {
        @rename($configFile, $configFile.'.old');
    }

    @copy($configSample, $configFile);

    $configContent = str_replace(
        array_keys($replacements),
        array_values($replacements),
        file_get_contents($configFile)
    );

    if (!file_put_contents($configFile, $configContent)) {
        throw new Exception("Oops! Failed writing new configurasion.\n");
    }

    if ($dbName != '' && file_exists($loader = __DIR__.'/loader.php')) {
        define('ROOT', dirname(__DIR__).DIRECTORY_SEPARATOR);
        require $loader;

        if (!app('db')->import(__DIR__.'/database.sql')) {
            throw new Exception("Oops! Failed importing database.\n");
        }
    }

    if ($base_url && strpos($base_url, 'http://localhost') === 0) {
        $path = str_replace('http://localhost', '', $base_url);
        $htaccess = file_get_contents('htaccess.txt');

        if (substr($path, 0, 1) === ':') {
            $path = '/';
        }

        $htaccess = str_replace('RewriteBase /', 'RewriteBase '.$path, $htaccess);

        if (!file_put_contents('.htaccess', $htaccess)) {
            throw new Exception("Oops! Failed writing new .htaccess.\n");
        }
    } else {
        @copy('htaccess.txt', '.htaccess');
    }

    // @chmod('../asset/uploads', 775);
} catch (RuntimeException $e) {
    $errors[] = $e->getMessage();
} catch (Exception $e) {
    $errors[] = $e->getMessage();
}

if (!empty($errors)) {
    array_unshift($errors, 'Something went wrong with message:'.PHP_EOL);
    e($errors, true);
}

foreach (['base_url', 'dbHost', 'dbUser', 'dbPass', 'dbName'] as $db) {
    $$db = $$db ?: '(empty)';
}

$in = [
    'Congratulation! this app successfuly installed with configuration: ',
    '   baseurl: '.$base_url
];

if ($cleardb) {
    $in[] = '  You\'re running on Heroku environment, please see your control panel.';
} else {
    $in[] = '  hostname: '.$dbHost;
    $in[] = '  username: '.$dbUser;
    $in[] = '  password: '.$dbPass;
    $in[] = '    dbname: '.$dbName;
}

e($in);

if ($dbName == '(empty)') {
    e([
        PHP_EOL.'Note:',
        '  Your database isn\'t installed yet, you can import it manualy using sample \'system/database.sql\' file. OR'.PHP_EOL
    ]);
    help();
}

exit;
